export enum AppPath {
  landing = "/",
  contextGeneralEdit = "/context/general",
  contextBankEdit = "/context/bank",
  contextSuperEdit = "/context/super",
  contextSharesEdit = "/context/shares",
  contextPropertyEdit = "/context/property",
  contextDefinedBenefitsEdit = "/context/definedBenefits",
  contextInflationEdit = "/context/inflation",
  contextLivingExpensesEdit = "/context/livingexpenses",
  scenarioAdd = "/context/scenario/add",
  scenarioEdit = "/context/scenario/:id",
  transferAdd = "/context/transfer/add",
  transferEdit = "/context/transfer/:id/edit",
  assetEdit = "/context/asset/:id/edit",
  assetAdd = "/context/asset/add",
  sheet = "/sheet",
  config = "/config",
  charts = "/charts",
  fileImport = "/file/import",
  fileExport = "/file/export",
  tools = "/tools",
  about = "/about"
}
