export enum AppPath {
  landing = "/",
  contextGeneralEdit = "/context/general",
  contextBankEdit = "/context/bank",
  contextSuperEdit = "/context/super",
  contextSharesEdit = "/context/shares",
  contextPropertyEdit = "/context/property",
  contextDefinedBenefitsEdit = "/context/definedBenefits",
  contextInflationEdit = "/context/inflation",
  contextLivingExpensesEdit = "/context/livingexpenses",
  scenarioAdd = "/context/scenario/add",
  scenarioEdit = "/context/scenario/:id",
  transferAdd = "/transfers/add",
  transferEdit = "/transfers/:id",
  assetEdit = "/assets/:id",
  assetAdd = "/assets/add",
  sheet = "/sheet",
  config = "/config",
  drawdowns = "/drawdowns",
  charts = "/charts",
  fileImport = "/file/import",
  fileExport = "/file/export",
  tools = "/tools",
  documentation = "/docs/scenarios",
  about = "/docs/about"
}
